server:
    port: 8888
    tomcat:
          basedir: E:\basedir

logging:
    level:
        tk.mybatis: INFO

mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    config-location:  classpath:mapper/config/sqlMapConfig.xml
    type-aliases-package: com.cn.meet.model.oracle


spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/meet
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


