server:
  tomcat:
    basedir: /home/temp/


logging:
  level:
    tk.mybatis: INFO


spring:
    datasource:
        url: jdbc:mysql://cdb-b9eywhzg.bj.tencentcdb.com:10148/meet?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: Hebzd*9eoK0@dBmW
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        maxActive: 50
        initialSize: 10
        maxWait: 60000
        minIdle: 1

    redis:
        host: localhost
        port: 6379
        password: hfnfn994etu
        timeout: 3000 # 超时时间
        lettuce:
          pool:
            max-active: 200 #连接池最大连接数（使用负值表示没有限制）
            max-idle: 20 # 连接池中的最大空闲连接
            min-idle: 5 #连接池中的最小空闲连接
            max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

    servlet:
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB


file:
     path:
        register: /home/register