spring:
    profiles:
        active: pro

server:
    port: 8888
    servlet:
        session:
          timeout: 43200s  # session 超时时间12小时
          cookie:
            name: sessionid_m


     # 支持https配置
    tomcat:
      remote-ip-header: "X-Forwarded-For"
      protocol-header: "X-Forwarded-Proto"
      protocol-header-https-value: "https"
      uri-encoding: "UTF-8"


mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    config-location:  classpath:mapper/config/sqlMapConfig.xml


